apps/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    path("product/<int:id>/", views.product_detail, name="product_detail"),
    path("wishlist/add/<int:product_id>/", views.wishlist_add, name="wishlist_add"),
    path("wishlist/", views.wishlist_view, name="wishlist"),
    path(
        "wishlist/remove/<int:product_id>/",
        views.remove_from_wishlist,
        name="remove_from_wishlist",
    ),
    # cart
    path("add-to-cart/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart_view, name="cart"),
    path("checkout/", views.checkout_view, name="checkout"),
    path(
        "order/<int:order_id>/process_payment/",
        views.process_payment,
        name="process_payment",
    ),
    path(
        "order-confirmation/<int:order_id>/",
        views.order_confirmation_view,
        name="order_confirmation",
    ),
    # orders
    path(
        "order-history/",
        views.customer_order_history_view,
        name="customer_order_history",
    ),
    path("cashier-orders/", views.all_orders_view, name="all_orders"),
    path("<int:order_id>/", views.order_detail_view, name="order_detail_view"),
    path(
        "to-be-processed/",
        views.orders_to_be_processed_view,
        name="orders_to_be_processed",
    ),
    path("delete/<int:order_id>/", views.order_delete_view, name="delete_order"),
    path("report/<int:order_id>/", views.order_report_view, name="order_report"),
    path("process/<int:order_id>/", views.order_process_view, name="order_process"),
    path(
        "confirm-payment/<int:order_id>/",
        views.confirm_payment_view,
        name="confirm_payment",
    ),
    path("payment/flutter/", views.payment_flutter_view, name="payment_flutter"),
]

apps/products/urls.py
# urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    # ** Category URLs **
    path("categories/", views.categories_list_view, name="categories_list"),
    path("categories/add/", views.categories_add_view, name="categories_add"),
    path(
        "categories/update/<str:category_id>/",
        views.categories_update_view,
        name="categories_update",
    ),
    path(
        "categories/delete/<str:category_id>/",
        views.categories_delete_view,
        name="categories_delete",
    ),
    # ** Volume URLs **
    path("volume/list", views.volume_list, name="volume_list"),
    path("volume/add/", views.volume_add_view, name="volume_add"),
    path(
        "volume/update/<int:volume_id>/", views.volume_update_view, name="volume_update"
    ),
    # ** Product Volume URLs **
    path(
        "volume/add/<int:product_id>/",
        views.add_product_volume_view,
        name="add_product_volume",
    ),
    path(
        "product_volume/update/<int:product_id>/<int:volume_id>/",
        views.update_product_volume_view,
        name="update_product_volume",
    ),
    path(
        "products/<int:product_id>/volumes/",
        views.product_volume_list_view,
        name="product_volume_list",
    ),
    path(
        "volumes/<int:volume_id>/delete/",
        views.delete_product_volume_view,
        name="delete_product_volume",
    ),
    # ** Product URLs **
    path("all", views.products_list_all, name="products_list_all"),
    path("", views.products_list_view, name="products_list"),
    path("add/", views.products_add_view, name="products_add"),
    path(
        "update/<str:product_id>/", views.products_update_view, name="products_update"
    ),
    path(
        "delete/<str:product_id>/", views.products_delete_view, name="products_delete"
    ),
    # ** Product Image URLs **
    path("product-image/", views.update_product_image, name="update_product_image"),
    path("product-image/list/", views.product_images, name="product_images"),
    path(
        "product-image/delete/<int:pk>/",
        views.delete_product_image,
        name="delete_product_image",
    ),
    # ** Stock Alerts **
    path("stock-alerts/", views.stock_alerts_view, name="stock_alerts"),
]

core/urls.py
# Import necessary modules and functions from Django
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

# Define the URL patterns for the project
urlpatterns = [
    # Admin route
    path("admin/", admin.site.urls),
    # Main application routes
    path("", include("apps.main.urls")),
    path("auth/", include("apps.authentication.urls")),
    path("customers/", include("apps.customers.urls")),
    path("supplier/", include("apps.supplier.urls")),
    path("products/", include("apps.products.urls")),
    path("inventory/", include("apps.inventory.urls")),
    path("sales/", include("apps.sales.urls")),
    path("orders/", include("apps.orders.urls")),
    path("finance/", include("apps.finance.urls")),
    path("blog/", include("apps.blog.urls")),
    # Social Authentication
    re_path(r"^oauth/", include("social_django.urls", namespace="social")),
    # Djoser authentication routes
]

# Additional URL patterns for debugging and media files in development mode
if settings.DEBUG:
    urlpatterns += [
        # Reload routes for browser refresh during development
        path("__reload__/", include("django_browser_reload.urls")),
        # Debug toolbar routes for debugging purposes
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    # Serve media files during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/products/models.py
from django.db import models
from django.forms import model_to_dict
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from apps.supplier.models import Supplier
from cloudinary.models import CloudinaryField
import cloudinary.uploader

# Define choices for product status
STATUS_CHOICES = [
    ("", "-- Choose status --"),
    ("ACTIVE", "Active"),
    ("INACTIVE", "Inactive"),
]

# Define choices for gender
GENDER_CHOICES = [
    ("", "-- Choose gender --"),
    ("Unisex", "Unisex"),
    ("Male", "Male"),
    ("Female", "Female"),
]

# Define choices for product type
PRODUCT_TYPE_CHOICES = [
    ("", "-- Choose product type --"),
    ("Roll-On", "Roll-On"),
    ("Spray", "Spray"),
]


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Name",
    )
    description = models.CharField(
        max_length=100, blank=True, verbose_name="Description"
    )

    class Meta:
        db_table = "category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Volume(models.Model):
    ml = models.IntegerField(unique=True, verbose_name="Volume in ML")

    def __str__(self):
        return f"{self.ml} ML"


class Product(models.Model):
    name = models.CharField(max_length=256, verbose_name="Product Name")
    description = models.TextField(verbose_name="Product Description")
    status = models.CharField(
        choices=STATUS_CHOICES, max_length=10, verbose_name="Status"
    )
    category = models.ForeignKey(
        Category,
        related_name="products",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Category",
    )
    volumes = models.ManyToManyField(
        Volume, through="ProductVolume", related_name="products"
    )
    supplier = models.ForeignKey(
        Supplier,
        related_name="products",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Supplier",
    )
    gender = models.CharField(
        choices=GENDER_CHOICES,
        max_length=10,
        default="Unisex",
        verbose_name="Targeted Gender",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")

    class Meta:
        db_table = "product"

    def __str__(self):
        return self.name

    def to_json(self):
        item = model_to_dict(self)
        item.update(
            {
                "id": self.id,
                "text": self.name,
                "category": self.category.name if self.category else None,
                "quantity": (
                    self.inventory.quantity if hasattr(self, "inventory") else 0
                ),
                "total_product": 0,
            }
        )
        return item

    @property
    def prefixed_id(self):
        return f"JBL{self.pk:03d}"


class ProductVolume(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_type = models.CharField(
        choices=PRODUCT_TYPE_CHOICES,
        max_length=10,
        default="Spray",
        verbose_name="Type",
    )
    volume = models.ForeignKey(Volume, on_delete=models.CASCADE)

    # Cost and Price determined by the selected volume for this product
    cost = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Cost Price"
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Selling Price"
    )
    image = CloudinaryField(
        "product_volume_image",
        validators=[FileExtensionValidator(allowed_extensions=["jpg", "jpeg", "png"])],
        null=True,
        blank=True,
    )

    class Meta:
        unique_together = ("product", "volume", "product_type")
        verbose_name = "Product Volume"
        verbose_name_plural = "Product Volumes"

    def save(self, *args, **kwargs):
        if self.image and not str(self.image).startswith("http"):
            upload_result = cloudinary.uploader.upload(
                self.image.file, folder="product_volume_images"
            )
            self.image = upload_result["url"]
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.product.name} - {self.volume.ml}ML (Cost: {self.cost}, Price: {self.price})"


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, related_name="images", on_delete=models.CASCADE
    )
    # image = models.ImageField(upload_to="product_images/", verbose_name="Product Image")
    image = CloudinaryField("image", blank=True, null=True)
    is_default = models.BooleanField(default=False, verbose_name="Is Default")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created at")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")

    class Meta:
        db_table = "product_image"
        verbose_name = "Product Image"
        verbose_name_plural = "Product Images"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Image for {self.product.name} (Default: {self.is_default})"

    def clean(self):
        # Ensure only one default image is set per product
        if self.is_default:
            default_image_exists = (
                ProductImage.objects.filter(product=self.product, is_default=True)
                .exclude(id=self.id)
                .exists()
            )

            if default_image_exists:
                raise ValidationError("Only one default image can be set per product.")

    def save(self, *args, **kwargs):
        # Ensure no other images are marked as default if this one is set as default
        if self.is_default:
            ProductImage.objects.filter(product=self.product, is_default=True).update(
                is_default=False
            )

        super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        if self.image and not str(self.image).startswith("http"):
            upload_result = cloudinary.uploader.upload(
                self.image.file, folder="product_images"
            )
            self.image = upload_result["url"]
        super().save(*args, **kwargs)

apps/products/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Category, Volume, ProductVolume, Product, ProductImage
from apps.inventory.models import Inventory


# =================================== category form ===================================
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "description"]
        widgets = {
            "name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter category name"}
            ),
            "description": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter category description",
                }
            ),
        }
        labels = {
            "name": "Category Name",
            "description": "Description",
        }


# =================================== volume form ===================================
class VolumeForm(forms.ModelForm):
    class Meta:
        model = Volume
        fields = ["ml"]
        widgets = {
            "ml": forms.NumberInput(attrs={"class": "form-control"}),
        }
        labels = {
            "ml": "Volume in ML",
        }


# =================================== ProductVolumeForm form ===================================
class ProductVolumeForm(forms.ModelForm):
    MAX_IMAGE_SIZE_MB = 10

    class Meta:
        model = ProductVolume
        fields = ["volume", "product_type", "cost", "price", "image"]
        widgets = {
            "volume": forms.Select(attrs={"class": "form-control"}),
            "product_type": forms.Select(attrs={"class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        self.product = kwargs.pop("product", None)
        super().__init__(*args, **kwargs)
        # Dynamically populate the volume choices
        self.fields["volume"].queryset = Volume.objects.all()

    def clean(self):
        cleaned_data = super().clean()
        volume = cleaned_data.get("volume")
        product_type = cleaned_data.get("product_type")

        # Check if a ProductVolume with the same product, volume, and product_type already exists
        if (
            ProductVolume.objects.filter(
                product=self.product, volume=volume, product_type=product_type
            )
            .exclude(id=self.instance.id)
            .exists()
        ):
            raise ValidationError(
                "Oops! This combination of volume and product type is already assigned to this product."
            )
        return cleaned_data

    def clean_image(self):
        image = self.cleaned_data.get("image")

        if image:
            image_size = image.size
            max_size = self.MAX_IMAGE_SIZE_MB * 1024 * 1024  # Convert MB to bytes

            if image_size > max_size:
                raise forms.ValidationError(
                    f"Image size should not exceed {self.MAX_IMAGE_SIZE_MB} MB."
                )

        return image

    def save(self, commit=True):
        product_volume = super().save(commit=False)
        if self.product:
            product_volume.product = self.product
        if commit:
            product_volume.save()
        return product_volume


# =================================== Inventory form ===================================
class InventoryForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = ["quantity", "low_stock_threshold"]
        widgets = {
            "quantity": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Enter stock quantity"}
            ),
            "low_stock_threshold": forms.NumberInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter low stock threshold",
                }
            ),
        }
        labels = {
            "quantity": "Stock Quantity",
            "low_stock_threshold": "Low Stock Threshold",
        }


# =================================== product form ===================================
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "name",
            "description",
            "status",
            "category",
            "gender",
            "supplier",
        ]
        widgets = {
            "name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter product name"}
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter product description",
                    "rows": 3,
                }
            ),
            "status": forms.Select(attrs={"class": "form-control"}),
            "category": forms.Select(attrs={"class": "form-control"}),
            "gender": forms.Select(attrs={"class": "form-control"}),
            "supplier": forms.Select(attrs={"class": "form-control"}),
        }
        labels = {
            "name": "Product Name",
            "description": "Description",
            "status": "Status",
            "category": "Category",
            "gender": "Gender",
            "suppliers": "Suppliers",  # Label for the suppliers field
        }


# =================================== CHILD PROFILE ===================================
class ProductImageForm(forms.ModelForm):
    image = forms.ImageField(required=False)

    class Meta:
        model = ProductImage
        fields = ["image"]

        labels = {
            "image": "Upload Product Image:",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["image"].widget = forms.FileInput(attrs={"accept": "image/*"})

    def clean_image(self):
        image = self.cleaned_data.get("image")
        return image

templates/products/categories.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container-fluid">
    <div class="row mb-3">
      <div class="col-md-12 d-flex justify-content-between align-items-center">
        <a href="{% url 'products:categories_add' %}" class="btn btn-success font-weight-bold"><i class="mdi mdi-plus mr-2"></i> Add Category</a>
        <div class="d-flex">
          <button title="Print" type="button" class="btn btn-success ml-2" onclick="printDiv('printMe')"><i class="mdi mdi-printer btn-icon-prepend"></i></button>
        </div>
      </div>
    </div>

    <!-- Search Form -->
    <form method="get" action="{% url 'products:categories_list' %}">
      <div class="input-group">
        <input type="text" class="form-control" name="search" value="{{ search_query }}" placeholder="Search by name" />
        <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i> Search</button>
      </div>
    </form>

    <!-- DataTable -->
    <div id="printMe" class="card shadow mb-4">
      <div class="card-header py-3">
        <h2>PRODUCTS CATEGORIES</h2>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="my-table" id="dataTable">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Description</th>
                <th colspan="2" class="text-center print-hide" style="width:15%">Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for c in categories %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ c.name }}</td>
                  <td>{{ c.description }}</td>
                  <td class="text-center print-hide">
                    <!-- Update button -->
                    <a href="{% url 'products:categories_update' c.id %}" class="text-decoration-none" onclick="return confirm('Are you sure you want to update this record?');"><button type="button" class="btn btn-warning btn-sm" data-bs-toggle="tooltip" title="Update category"><i class="bi bi-pencil"></i></button></a>
                  </td>
                  <td class="text-center print-hide">
                    {% if user.profile.role == 'administrator' or user.profile.role == 'manager' %}
                      <!-- Delete button and modal -->
                      <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ c.id }}" title="Delete category"><i class="bi bi-trash"></i></button>

                      <!-- Delete Modal -->
                      <div class="modal fade" id="deleteModal{{ c.id }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ c.id }}" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="deleteModalLabel{{ c.id }}">Delete Category</h5>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">X</button>
                            </div>
                            <div class="modal-body">
                              Are you sure you want to delete the category: <h3>{{ c.name }}?</h3>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                              <a href="{% url 'products:categories_delete' c.id %}" class="text-decoration-none"><button type="button" class="btn btn-danger">Delete</button></a>
                            </div>
                          </div>
                        </div>
                      </div>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- Pagination -->
        <div class="pagination">
          <span class="step-links">
            {% if page_obj.has_previous %}
              <a href="?page=1&search={{ search_query }}">&laquo; first</a>
              <a href="?page={{ page_obj.previous_page_number }}&search={{ search_query }}">previous</a>
            {% endif %}

            <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>

            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}&search={{ search_query }}">next</a>
              <a href="?page={{ page_obj.paginator.num_pages }}&search={{ search_query }}">last &raquo;</a>
            {% endif %}
          </span>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/products/product_image_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
    <div class="row mb-3">
        <div class="col-md-12 d-flex justify-content-between align-items-center">
            <a href="{% url 'products:products_list' %}">
                <button type="button" class="btn btn-info font-weight-bold">
                    <i class="mdi mdi-arrow-left-bold mr-2"></i>
                    Go back
                </button>
            </a>
            <div class="d-flex">
                <a href="{% url 'products:product_images' %}" class="btn btn-success font-weight-bold ml-2">
                    <i class="mdi mdi-cloud-download mr-2"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3>{{ table_title|upper }}</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <select name="id" id="dropdown" class="chzn-select" required>
                            <option value="" selected disabled>Search product...</option>
                            {% for product in products %}
                            <option value="{{ product.id }}">{{ product.name }}
                            </option>
                            {% endfor %}
                        </select>
                        <br /><br />
                        <!--  -->
                        {{ form|crispy }}
                        <div class="form-group mt-4 mb-0">
                            <button type="submit" class="col-md-12 btn btn-dark"
                                onclick="return confirm('Are you sure you want to proceed?') && validateForm()">
                                Upload Image</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/products/products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container-fluid">
    <div class="row mb-3">
      <div class="col-md-12 d-flex justify-content-between align-items-center">
        <a href="{% url 'products:products_add' %}" class="btn btn-dark ml-2">
          <i class="mdi mdi-plus mr-2"></i>
          Add Product
        </a>
        <div class="d-flex">
          <a href="{% url 'products:update_product_image' %}" class="btn btn-success font-weight-bold ml-2"><i class="mdi mdi-cloud-upload mr-2"></i></a>
          <button title="Print" type="button" class="btn btn-success ml-2" onclick="printDiv('printMe')"><i class="mdi mdi-printer btn-icon-prepend"></i></button>
        </div>
      </div>
    </div>

    <!-- Search Form -->
    <div class="row mb-3">
      <div class="col-md-12">
        <form method="get" action="{% url 'products:products_list' %}">
          <div class="input-group">
            <input type="text" class="form-control" name="search" value="{{ search_query }}" placeholder="Search by name or category or supplier" />
            <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i> Search</button>
          </div>
        </form>
      </div>
    </div>

    <!-- DataTable -->
    <div id="printMe" class="card shadow mb-4">
      <div class="card-header py-3">
        <h3>{{ table_title|upper }}</h3>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="my-table" id="dataTable">
            <thead>
              <tr>
                <th>#</th>
                <th>Product</th>
                <th>Category</th>
                <th>Gender</th>
                <th>Supplier</th>
                <th class="text-center print-hide">Status</th>
                <th colspan="3" class="text-center print-hide">Action</th>
              </tr>
            </thead>
            <tbody>
              {% if products %}
                {% for product in products %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.category }}</td>
                    <td>{{ product.gender }}</td>
                    <td>{{ product.supplier }}</td>
                    <td class="text-center print-hide">
                      {% if product.status == 'ACTIVE' %}
                        <span class="badge badge-success" style="font-size:0.8em;">{{ product.status }}</span>
                      {% elif product.status == 'INACTIVE' %}
                        <span class="badge badge-danger" style="font-size:0.8em;">{{ product.status }}</span>
                      {% endif %}
                    </td>
                    <td class="text-center print-hide">
                      <a href="{% url 'products:products_update' product.id %}" class="text-decoration-none" onclick="return confirm('Are you sure you want to update this record?');"><button type="button" class="btn btn-warning btn-sm" data-bs-toggle="tooltip" title="Update product"><i class="bi bi-pencil"></i></button></a>
                    </td>
                    <td class="text-center print-hide">
                      <a href="{% url 'products:product_volume_list' product.id %}" class="text-decoration-none"><button type="button" class="btn btn-info btn-sm" data-bs-toggle="tooltip" title="Manage Volumes"><i class="bi bi-box"></i></button></a>
                    </td>
                    {% if user.profile.role == 'administrator' or user.profile.role == 'manager' %}
                      <td class="text-center print-hide">
                        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ product.id }}" title="Delete product"><i class="bi bi-trash"></i></button>

                        <div class="modal fade" id="deleteModal{{ product.id }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ product.id }}" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="deleteModalLabel{{ product.id }}">Delete Product</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">X</button>
                              </div>
                              <div class="modal-body">
                                Are you sure you want to delete the product: <h3>{{ product.name }}?</h3>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                <a href="{% url 'products:products_delete' product.id %}" class="text-decoration-none"><button type="button" class="btn btn-danger">Delete</button></a>
                              </div>
                            </div>
                          </div>
                        </div>
                      </td>
                    {% endif %}
                  </tr>
                {% endfor %}
              {% else %}
                <tr>
                  <td colspan="7" class="text-center">No products available</td>
                </tr>
              {% endif %}
            </tbody>
          </table>
        </div>
        <nav aria-label="Page navigation">
          <ul class="pagination justify-content-center">
            {% if products.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ products.previous_page_number }}&search={{ search_query }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;</span>
              </li>
            {% endif %}

            {% for num in products.paginator.page_range %}
              {% if products.number == num %}
                <li class="page-item active">
                  <span class="page-link">{{ num }}</span>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ num }}&search={{ search_query }}">{{ num }}</a>
                </li>
              {% endif %}
            {% endfor %}

            {% if products.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ products.next_page_number }}&search={{ search_query }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&raquo;</span>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
  </div>
{% endblock %}